### ISSUE TITLE
[Bug fix] manifest.json error

### ISSUE THREAD

**Issue by juunone** [developer-1px/adorable-css#11]
안녕하세요 if.kakao에서 발표해주신 내용 잘봤습니다 👍🏻 
올려주신 figma 플러그인 설치하는 중에

![manifest](https://user-images.githubusercontent.com/35126809/142167453-01657e02-58c5-45cf-b44c-86fe5c0c5185.PNG)

위 와 같이 `editorType` 이 빠져서 정상적으로 import가 안되는 상황이 발생했습니다.
- - -
```
"editorType": ["figma"]
```
위와 같이 `editorType` 추가로 이슈 해결해서 공유드립니다.
감사합니다 🙏🏻

**Comment by developer-1px** [comment]
감사합니다. 
플러그인을 만들때는 figjam이 없던 시절이라 확인도 안해보고 있었네요. ㅠㅠ
덕분에 외부 공개 타이밍에 정상동작할 수 있도록 수정할 수 있었습니다.  :) 

https://github.com/developer-1px/adorable-css/commit/3a8b0a691fc8f13a60dff09fe071c5cbfe49a1ff#diff-043d6f76444bd8eace9a6786179c382734fc193b68c92f433851b3c449bf7094
