### ISSUE TITLE
혹시 웹컴포넌트에서도 사용할 수 있나요? 

### ISSUE THREAD

**Issue by easylogic** [developer-1px/adorable-css#12]
안녕하세요.  

멋진 프로젝트를 알게 되서 처음으로 이슈를 남겨 봅니다. 

웹컴포넌트 형태로 만들고 싶은 프로젝트가 있는데요.  

이 프로젝트가 눈에 띄네요. 

같이 한번 써봤으면 좋겠는데 혹시 웹컴포넌트 같은 것도 지원이 되나요?

**Comment by developer-1px** [comment]
ㄴ 와! 저야 말로 영광입니다. 만들고 계신 디자인 툴 눈여겨 보고 있습니다. 디자이너와 개발자가 같은 툴을 써서 별도의 handoff 과정 없이 코드와 디자인을 공유하는 형태의 디자인 툴이 있었으면 좋겠다고 생각하고 있었거든요.

1
AdorableCSS는 일종의 번들툴이니 클라이언트 라이브러리 같은 형태로는 아직 지원하고 있지 않습니다.
외부 배포용 웹 컴포넌트 개발을 생각하시고 계시는 거라면
저라면 vite + svelte(web component compile) 같은 방식으로 개발 및 배포할 수 있을 거라고 생각합니다.

2
아니면 현재 홈페이지 REPL과 같이 innerHTML을 전달하면 그에 맞는 css를 자동으로 생성해서 <style> 엘리먼트에 추가를 해주는 방식으로
런타임 CSS in JS와 같은 형태로 클라이언트 라이브러리를 만들어서 제공을 할 수 있을 것 같습니다.
https://developer-1px.github.io/adorable-css/ 

3
생각하고 계신 웹 컴포넌트의 지원의 형태의 구체적인 모습까지는 몰라서 설명 드리기 힘드네요.
구체적인 지원 형태나 해결해야 하는 문제 상황에 대해 알려주시면 답변 드리도록 하겠습니다.

감사합니다. :)

**Comment by easylogic** [comment]
제가 하고 싶은 건  all in one 형태로 동작하는 web component 입니다. 

https://github.com/easylogic/mime  

여기에 대략적으로 스펙을 적고 있는데요. mime type 에 관련된 것을 태그 하나로 모든 것을 표현하는 방식입니다. 

이걸 webcomponent 형태로 만들 예정인데, web component 안에서 style 을 컴포넌트 처럼 관리가 쉽지 않은 걸로 알고 있어서요. 

emotion 같은 css in js 도 약간 돌려서 사용하는 느낌이 나서  혹시나 하고 여줘봤습니다.  ^^   

일단 하고 계시는 방식 자체가  구조적적으로 동적으로 css 를 쉽게 만들 수 있을 듯해서요. 
구조만 맞으면 웹컴포넌트 내부를 확장할 수 있는 방식을 할 수 있을지 궁금했습니다. 

답변 해주셔서 감사합니다. ^^ 

ps. 

vite + svelte 쪽을 한번 볼게요. 좋은 정보 감사합니다.

**Comment by developer-1px** [comment]
네~ svelte의 web-component에서 확인해봤는데 adorableCSS를 customElement로 빌드를 하기 위해서는 몇가지 과정이 필요할것 같네요.

외부에 배포하기 위한 컴포넌트 개발이 목적이시라면 굳이 adorableCSS을 쓰지 않고 그냥 svelte에서 지원하는 <style>태그를 이용해서 개발해보심이 어떨까 생각합니다. 

바로 적용해보기 좋은 참조 링크 공유 드립니다. 

https://www.thisdot.co/blog/web-components-with-svelte

좋은 하루 되세요 :)

**Comment by easylogic** [comment]
좋은 자료 알려주셔서 감사합니다. ^^ 

지금 당장은 제쪽에서 적용을 못할 것같긴 하지만 
하시는 프로젝트 계속 발전하기를  응원하겠습니다.
