### ISSUE TITLE
혹시 js 확장자도 기본 ext 에 넣어주실 수 있나요? 

### ISSUE THREAD

**Issue by easylogic** [developer-1px/adorable-css#14]
개인적으로 작업하는 프로젝트를 이번에 vite 기반으로 바꿔서 같이 써볼려고 하는데요.  

```js
  ext: ["svelte", "vue", "tsx", "jsx", "mdx", "svx", "html"], 
```

기본 파싱되는 확장자가 위와 같이 되어 있는 것 같습니다. 

그래서 일단은 아래처럼 설정했습니다. 

```js
    adorableCSS({
      ext: ['js'],
    }),
```

혹시 js 확장자도 기본 ext 에 넣어주실 수 있나요?

**Comment by developer-1px** [comment]
ts와 js는 default에서 제외한 점은 컴포넌트와 관련되지 않은 파일들을 계속 검사해야 하다보니 퍼포먼스 및 불필요한 css가 생성되기 때문이었습니다

현재 대부분 많이 사용하는 React, vue, svetle 기준으로 컴포넌트를 쓰는 파일들이 다른 확장자를 쓰고 있기 때문에 그러한 확장자만 default로 설정이 되었습니다

지금처럼 config에서 설정을 바꿀수는 있기때문에 굳이 ts나 js를 default로 가져갈 필요는 없다고 생각을 합니다

default에 넣고자 하른 보통의 입문자들을 위해 zero-config로 할 수 있기를 바람입니다.

취지에 공감해주시길 바라며 보내 주신 제안 너무 감사합니다. 혹 취지에 부합할 다른 제안이 있다면 얼마든지 알려주세요~ 감사합니다 :)

**Comment by easylogic** [comment]
아 ~  그런 의도를 가지고 계신거면  제쪽에서 따로 확장자를 하나 가상으로 만들어서 그것만 적용하도록 해야겠네요. 

말씀하신대로 모든 js 가 스타일을 사용하는게 아니다보니  확실히 성능 측면에서 좋지 않을 수 있겠다는 생각이 듭니다. 

좋은 말씀 감사드려요. ^^

**Comment by developer-1px** [comment]
확장자는 동일하나 테스트와 같이 .spec.js이나 /components/**.js 와 같은 glop을 통한 방법을 적용해보도록 하겠습니다

**Comment by easylogic** [comment]
아 그렇게만 되도 ^^ 상당히 편할 것 같습니다. 완전 좋네요.

**Comment by developer-1px** [comment]
기존의 ext 옵션을 삭제하고 glob기반으로 변경하였습니다.

// default
{
  include: ["**/*.{svelte,tsx,jsx,vue,mdx,svx,html}"]
}

원하는 시는대로 폴더별로 구분을 하시거나, 

adorableCSS({
  include: ["src/components/**/*.js"]
})

아니면 파일이름 규칙등으로 작업을 해보시길 바랍니다.
adorableCSS({
  include: ["**/*.comp.js"]
})

혹시 문제가 있다면 코멘트 남겨주세요. 제안 감사드립니다. :)

**Comment by easylogic** [comment]
잘 되는 것 같습니다.  

혹시 몰라서 제 프로젝트 내부에 jsx, svelte 도 같이 테스트 했는데 잘 됩니다. 

감사합니다. ^^
