### ISSUE TITLE
(리액트) svg 에서 동작하지 않음

### ISSUE THREAD

**Issue by zineeworld** [developer-1px/adorable-css#15]
div, span 기타 태그와 달리 svg에 적용한 클래스명은 제대로 생성이 되지 않는 것 같습니다....!

# 예) p(2) 에 대한 스타일이 보이지 않고 있음
![image](https://user-images.githubusercontent.com/12759765/146514246-d79215a6-855d-4f16-a185-3f8660e5c64a.png)

**Comment by developer-1px** [comment]
svg에서 적용이 되지 않던 현상을 수정하였습니다.
