### ISSUE TITLE
겹치게 배치하는 오브젝트가 플러그인에서 제대로 보이지 않는 이슈

### ISSUE THREAD

**Issue by AkzidensGrotesk** [developer-1px/adorable-css#19]
안녕하세요, 사내 개발팀 직원의 소개로 이 플러그인을 접하게 된 디자이너입니다!
제가 작업한 UI디자인이 개발자에게 전달되어 실제 웹/앱에서 어떻게 보여지는 지를 고민하던 중 좋은 프리뷰 플러그인을 발견하여 기쁘고 감사드립니다.
그와중에 한 가지 고민사항이 생겨 이슈를 남기게 되었습니다.
개발상에서는 오브젝트의 포지션을 음수로 지정할 수 있는 것으로 알고 있습니다. 하지만 슬프게도 Figma의 Autolayout은 음수 간격을 지정할 수가 없어서.....푸시알림과 같이 다른 오브젝트와 겹쳐서 배치해야 하는 경우에는 Frame을 사용하고 있습니다.

readme 를 읽어보며 모든 작업을 Autolayout화 하기로 협의하고 그에 맞추어 플러그인을 제작하셨다는 내용을 발견했습니다.
그래서 겹쳐지는 오브젝트를 컴포넌트화 시키고 Autolayout으로 묶거나, Frame에 요령을 피운 후 Autolayout으로 구성해보기도 했으나 부족한 저의 실력으로는 플러그인을 실행했을 때 원하는대로 나오는 방법을 찾을 수가 없었습니다....ㅠㅠㅠㅠ

그리하여 저와 같이 오브젝트를 겹쳐서 배치해야 할 경우(디자인)가 발생하셨다면, 이를 어떻게 작업하여 플러그인에서 깔끔하게 보이게 가능할지 자문을 구하고 싶습니다.
혹은 이러한 경우/디자인이 없으셨다면, 플러그인에서 프레임도 인식할 수 있도록 해주실 수 있을 지 문의를 드립니다.

제가 예시로 만든 피그마는 바로 이것입니다! https://www.figma.com/file/bnU1eZWRiZCQI1fyntf3er/test-list-push?node-id=0%3A1

![스크린샷 2021-12-29 오후 2 32 11](https://user-images.githubusercontent.com/96810052/147631393-7d8385c2-c5d0-40d7-a369-8fdf7e980c78.png)

**Comment by developer-1px** [comment]
안타깝게도 figma에서는 AutoLayout의 경우는 이처럼 겹치는 오브젝트에 대한 기능을 지원하지 않으므로 혹시나 계속 시도하실 까봐 AutoLayout으로는 해당 UI를 만들 수 없다는 점 미리 답변 남겨드립니다.

figma Frame의 Constraints를 이용하여 relative와 absolute를 만들어내는 기능은 현재 개발 중에 있습니다. 이부분은 개발이 완료되면 따로 공유 드리도록 하겠습니다. 일단 사내 개발자 분에게는 현재상황을 공유하고 preview의 코드를 참고만 해서 개발을 해주시라고 알려주시기 바랍니다.

그리고 원과 함께 텍스트를 만들 경우에는 Frame을 이용하고 border-radious: 100%와 Auto-layout의 가운데 정렬을 이용하시면 좋습니다. (그래야 마크업에서 쓸 수 있는 코드가 됩니다.)

figma가 마크업을 만들기 위한 툴이 아니나보니 이 플러그인이 디자이너에게도 개발자에게 제약을 주는 상황이긴 합니다. 완벽한 export라기 보다는 편의를 도모해주는 도구 선에서 이해를 해주시고 조금씩 기능을 더 붙여서 정말 쓰기 편한 도구로 발전 시켜보겠습니다. 감사합니다.

**Comment by AkzidensGrotesk** [comment]
와아아 빠른 답변 감사합니다. 더불어 작업 방식에 대한 코멘트도 감사드립니다! 덕분에 개발팀과 더욱더 원활한 작업을 할 수 있을 것 같아요.
멋지게 업그레이드 되는 플러그인을 기대하겠습니다 :)

**Comment by developer-1px** [comment]
우선은 해당 UI를 만들 수 있는 Constraints의 top, right, bottom, left 기능을 먼저 추가하였습니다. (center, scale은 아직 안되요) git pull을 통해서 플러그인을 업데이트 해주세요.

겹치는 요소의 경우 Frame 2개를 겹쳐둔 뒤에 복수개를 선택하고 Frame Selection을 하면서 Overlay로 표기할 수 있습니다.

지금 배지의 경우 기준선이 우측 상단일 가능성이 높기 때문에 빨간 배지 Constraints를 right, top 으로 설정하시면 될 것 같습니다.

figma의 경우 베이스는 디자인 툴이다 보니 조금 귀찮은 작업들이 많으실거에요. 아이콘등을 그리는 게 아니라 개발에서 HTML등으로 만들어내기 위해서는 전부 Frame 기반으로 작업이 되어야 합니다. 동그라미도 Circle이 아니라 Frame에 border-radious를 100으로 준다거나 하는 식으로 말이죠. 그리고 가운데 글자도 AutoLayout으로 가운데로 설정해서 글자를 집어넣는 식...

홍보를 할때는 짠~ 하고 만들어집니다 라고 했지만 실상은 디자이너분들의 피, 땀, 눈물이 섞인 결과물이었답니다. 대신 개발자들이 편해지는 만큼 나중에 디자인 바꿔주세요! 라고 요구하는게 어렵지 않게 되고 내가 한 디자인이 왜 이상하게 구현된거죠? 하는 부분은 줄어들거에요 :)

요청해주신 덕분에 동기부여가 되어 빨리 작업이 되었습니다. 언제든 필요한 것들이 있으면 이슈 남겨 주세요.

## 디자이너분들을 위한 작업 가이드

> 개발과 디자인의 방식의 차이로 인해서 레이어를 겹쳐서 그리는 방식이 아니라 구조적으로 만들어야만 개발에서 바로 사용할 수 있습니다. figma는 디자인 툴이기 때문에 이러한 방식을 강제하지 못합니다. 그래서 플러그인을 제대로 쓰고 개발하기 좋은 형태를 만들기 위한 가이드를 기록합니다. (추후 멋짓 문서로 보강해보곘습니다!)   

1. 모든 요소들은 Frame과 Text을 이용해서 구조적으로 작성을 합니다. Rectangle과 Circle을 이용해서 겹쳐서 그리지 않습니다.
2. Circle의 경우 Frame의 border-radius를 이용해서 그립니다.
3. 레이아웃은 가급적 Autolayout을 이용하여 작업합니다.
4. 겹치는 Overlay를 표현해야하는 경우 Frame을 겹쳐둔뒤 선택해서 Frame Selection(option + cmd + G) 을 사용해줍니다. (Group Selection를 사용하지 않습니다. Group Selection를 사용할 경우 Constraints 기능을 쓸 수 가 없습니다.)

![image](https://user-images.githubusercontent.com/66650330/147711339-8af3d418-9542-433e-93e1-664c3de217ca.png)

![image](https://user-images.githubusercontent.com/66650330/147711375-c1db3609-b64a-4d91-80b3-cf1a3cb6932b.png)

**Comment by AkzidensGrotesk** [comment]
저는 직접 코딩은 할 수 없더라도 UI 디자이너라면 개발자와의 간극을 줄일 수 있는 방법을 항상 고민해야한다고 생각합니다.
그렇기에 Figma는 다른 UI 디자인 툴보다 개발자의 구현 방식에 가깝게 작업이 가능한 것을 깨닫고 열심히 익히는 중인데, 디자이너를 위한 가이드까지 이렇게 정리를 해주시니...아침부터 감동의 눈물을 흘렸습니다...
작업해둔 오브젝트 구조를 수정하고 플러그인을 업데이트해서 작동해보겠습니다. 이걸 토대로 응용해볼 수 있는 방법도 이것저것 떠오르고 있어 잔뜩 실험해봐야겠어요. 다시 한 번 감사드립니다! 😃 😃 😃

**Comment by developer-1px** [comment]
감사합니다. 개발자들에게 사랑받는 디자이너가 되시겠네요! +_+bbb

현재는 디자인 작업 시즌이 끝나고나니 스스로가 더 이상 업데이트의 필요성을 못느껴서 업데이트에 소홀해지고 있습니다. 이 이슈제보가 저에게 너무 좋은 자극이 되었고 미뤄둔 숙제같던 업데이트를 이렇게나 빨리 선 보일 수 있게 되어 너무 감사드립니다.

실험 얼마든지 하시면서 좋은 아이디어들이 있으면 언제든 이슈 남겨주세요. :)
