### ISSUE TITLE
font-family 를 어떻게 사용해야하나요?

### ISSUE THREAD

**Issue by pksung1** [developer-1px/adorable-css#34]
Helvetica Neue 폰트를 적용하려고하는데 어떻게해도 적용이 안되서 이슈 남겨드립니다 😢 

```
fontFamily(Helvetica Neue)
fontFamily('Helvetica Neue')
font-family(Helvetica Neue)
font-family('Helvetica Neue')
font-family(--font-ticket-1)
```

Vite react-ts 를 사용하고 있습니다!

**Comment by developer-1px** [comment]
안녕하세요. 질문 감사합니다.

1
띄어쓰기를 할 수 없는 class 문법의 특성 상 괄호안의 값에는 띄어쓰기를 포함할 수 없습니다.
AdorableCSS에서는 모든 띄어쓰기를 /를 통해서 구분하고 있습니다. ex) p(5/10)  {padding:5px 10px;}
따라서 Helvetica Neue는 font-family(Helvetica/Neue) 라고 사용하시면 됩니다.

2
실전에서는 font-family의 경우에는 아래처럼 css variable을 이용하여 등록을 하시는 편이 더 나을 수 있습니다.

font-family(--font-title)

<style>
:root {
--font-title: 'Helvetica Neue', sans-serif
}
</style>

더 궁금한 게 있다면 얼마든지 답변 남겨주세요! 감사합니다 :)

**Comment by pksung1** [comment]
아하 / 이걸로 스페이스를 구분하는군요! 감사합니다 해결됬습니다!

font-family(--font-ticket-1) 이것도 정상적으로 잘되네요! 👍 👍
