### ISSUE TITLE
background-image에 url() 함수를 사용하고싶습니다! 방법이 있을까요?

### ISSUE THREAD

**Issue by pksung1** [developer-1px/adorable-css#35]
background-image에 url() 함수를 사용하고싶습니다! 방법이 있을까요?

```
background-image(url(main.png)) // X
background-image(url/(main.png/)) // X
bg(url(main.png)) // X
```

위 방법을 시도했으나 url때문에 안되더라구요 ㅠㅠ 방법이 있을까요?

**Comment by developer-1px** [comment]
아~ 아직 해당 기능 개발이 안되었어요. 추가되면 바로 공유 하겠습니다 :)

**Comment by developer-1px** [comment]
## 0.6.8
- ✨ bg(url(...)) background-image:url(...)
- ✨ bg(http...), bg(./), bg(/...) background-image:url(...)
- 🐛 transition(none)이 되지 않던 버그를 수정했습니다.

제보해주신 bg 기능을 추가하였습니다. url이 있거나 http, 혹은 . / 로 시작하는 값일 경우에는 background-image로 처리하도록 수정하였습니다.
제보 너무 너무 감사합니다 :)

**Comment by pksung1** [comment]
감사합니다! 제 개인프로젝트에서 사용중이라 어려운거나 불편한거 있으면 이슈 계속 남길것같아요 ㅎㅎ..
좋은 오픈소스 만들어주셔서 감사합니다~

**Comment by developer-1px** [comment]
너무 감사하죠! 그토록 기다리던 실사용자 피드백 너무 너무 감사합니다!!
어떠한 의견이든 개선할 의지가 있어요!! ㅋㅋ 뭐든 어렵거나 불편하거 있으면 알려주세요.
원하신다면 1:1 개인 교습도 가능합니다. ㅋㅋ
문서화 관련 아이디어든 학습곡석에 대한 문제든 뭐든 환영합니다.

고맙습니다!!
