### ISSUE TITLE
README outdated link

### ISSUE THREAD

**Issue by heli-os** [developer-1px/adorable-css#51]
안녕하세요, 리드미를 읽다가 깨진 링크가 있어서 제보 드립니다.

정상 링크로 바꾸는 PR을 올려볼까 했는데 정상 링크를 못찾겠네요..🤔

오류 링크 존재 부분
 - https://github.com/developer-1px/adorable-css/blob/master/README.md?plain=1#L167
 - https://github.com/developer-1px/adorable-css/blob/master/README.md?plain=1#L172

의도된 내용일까요?

**Comment by developer-1px** [comment]
이슈를 올려주시고 나서 바로 답변을 드리려고 했다가 수정이 되면 답변을 드려야지 하고 있다가 어느새 1주일이나 넘겨버렸네요 ㅠ 소중한 제보 너무 감사드리며 알려주신 링크가 제대로 동작하도록 수정하였습니다. 확인 감사드립니다.
