### ISSUE TITLE
tailwind와 차별화된 adorable-css만의 장점을 좀 더 명확하게 명시하면 좋을 것 같습니다.

### ISSUE THREAD

**Issue by wirekang** [developer-1px/adorable-css#54]
처음 이 프로젝트를 알게 되고 난 후 [공식 홈페이지](https://developer-1px.github.io/adorable-css), [/docs](https://developer-1px.github.io/adorable-css) 를 읽고 나서 든 생각은 "문법만 살짝 다른 tailwind 아닌가?" 였습니다. 블로그에 작성하신 글도 인상 깊게 읽었지만 tailwind와 차별화된 adorable-css만의 장점을 언급하는 부분은 거의 없어서 아쉬웠습니다. 블로그에서 언급하신 대로 복잡한 selector나 flexbox등 이 프로젝트의 장점을 tailwind와 직접적인 비교를 통해 보여주시면 좋을 것 같습니다.

**Comment by developer-1px** [comment]
좋은 지적 감사드립니다. 사실 이 프로젝트를 만들때만 하더라도 tailwindCSS에서는 JIT 기능이 만들어지지 않았었고 w-2 w-3 등이 4px 기준으로 만들어져 있어서 tailwindCSS로는 내가 원하는 디자인을 만들 수가 없던 것이 가장 큰 아쉬움이었기 때문에 그점을 중점으로 작성하긴 했습니다만, 그후 tailwindCSS에서도 JIT이 출시가 되면서 가장 큰 차별화 포인트는 사라지기는 했네요.

그 밖의 가장 큰 장점이라고 하면 언급해주신 문법만 살짝 다른 이라는 포인트도 중요하게 생각하고 있습니다. 특히 제일 자주 쓰이는 flexbox와 position 등에 대해서 hbox(right), vbox, gap, layer(top) 등의 직관적인 레이아웃 문법을 통해서 기존 tailwindCSS로 작성하는 것보다 훨씬 더 빠르게 디자인 작업을 직관적으로 할 수 있게 된 점이 실제로 tailwindCSS 대신 사용하고 계시는 분들이 말하는 가장 큰 장점이에요.

그밖에 모든 Selector를 지원한다거나, important, .selected:c(red) 처럼 class와 함께 사용하는 방식들도 실무에서 굉장히 유용하고 편리하게 쓰이는데 이렇게 말로만 쓰기 보다는 말씀해주신대로 차별화된 포인트에 대해서 한번 잘 정리된 문서를 작성해보는게 좋겠네요.

관심가져주시고 알려주셔서 감사합니다. 
사내에서만 쓰다보니까 뭔가 구전으로만 전파하다보니 문서화에 소홀하고 있었는데 뜨끔하네요. ㅎ

고맙습니다!
문서화 작업이 고도화 되면 또 공유 드리겠습니다.
❤️

**Comment by developer-1px** [comment]
https://developer-1px.github.io/adorable-css/background

홈페이지에 tailwind와 전격비교는 아니지만 어떻게 다른지 소개하는 글을 작성해보았습니다. tailwindCSS와 직접적인 비교글은 아니지만 가지고 있는 원고를 바탕으로 한번 정리해보았습니다.

기회가 된다면 조금 더 tailwindCSS와는 뭐가 어떻게 다른지 설명할 수 있는 글을 작성해보도록 하겠습니다. 감사합니다.

**Comment by developer-1px** [comment]
https://velog.io/@teo/adorablecss-better-then-tailwindcss

제안주신 내용에 맞는 새로운 문서를 작성했습니다.
오래 걸렸네요. 
너무 너무 감사드립니다.
