### ISSUE TITLE
layer position 조작도 향상

### ISSUE THREAD

**Issue by tooooo1** [developer-1px/adorable-css#55]
layer(left+top)일 시 left:0, top:0으로 adorable은 편리하게 변환되는데요.

그렇지만 추가적으로 커스텀 할 때에는 다음과 같이 추가해야 해요.

`
layer(left+top), left(10), top(10)
`

더 편리하게 adorable은 바뀔 수 있을 것 같아요. 다음과 같이요.

`
layer(left: 10+ top: 10)
`

어떠신지 궁금합니다!

**Comment by developer-1px** [comment]
소중한 제안 너무 감사합니다. 제안을 검토해서 아래와 같이 layer에 추가적인 기능을 만들었습니다.
이제 offset을 함께 지정할 수 있고 outside 방향으로도 지정할 수 있는 기능이 추가되었습니다.

1.2.8
- ✨layer(top:10) 과 같이 layer에 offset을 지정할 수 있는 기능을 추가하였습니다. 
- ✨layer(top+outside) 와 같이 부모 엘리먼트의 바깥쪽을 기준으로 붙이는 기능이 추가되었습니다.
