### ISSUE TITLE
Sveltekit에서는 vite 기반에서 간혹 css 업데이트가 되지 않는 현상이 발생해요.

### ISSUE THREAD

**Issue by developer-1px** [developer-1px/adorable-css#57]
현재 +layer.svelte에서 import "@adorable.css" 를 통해서 vite 업데이트시 css가 업데이트가 되도록 작성이 되어 있는데,
라우터 이동시 css 적용이 누락되는 경우가 있습니다. 이 경우 해당 router의 +page.svelte 파일 수정을 하면 HMR이 발동이 되어 업데이트가 됩니다.
어떻게 수정을 해야할 지 파악 중에 있습니다.

현재 1가지 방법으로는

import "@adorable.css" 대신
import "adorable-css"를 입력하면 vite watch기반이 아니라 cdn 방식으로 개발모드에서는 훨씬 더 쾌적한 환경에서 작업을 할 수 있습니다.

다만 빌드를 할 경우에는 다시 import "@adorable.css" 로 바꿔줘야 하는 번거로움이 존재합니다.

SvelteKit에서 개발모드와 빌드모드에서 둘 다 작동할 수 있도록 개발하고 있는 중입니다.

**Comment by composite** [comment]
음... 좀 번거롭지만 preprocess 에 속하도록 하는 방법을 써야 하나 싶네요.

**Comment by developer-1px** [comment]
svelteKit 버전이 올라가면서 자동으로 해당 문제가 해결이 되었습니다 ^^
