### ISSUE TITLE
공식 홈페이지의 튜토리얼의 스크롤에 오류가 있는 것 같습니다.

### ISSUE THREAD

**Issue by nadering** [developer-1px/adorable-css#59]
안녕하세요, 최근에 프론트엔드 공부를 시작해서 우연히 AdorableCSS를 접하였는데 Component 기반 + Atomic-CSS가 굉장히 매력적으로 느껴지는 것 같아 AdorableCSS도 공부하고 있습니다.

기능 확인을 위해 공식 홈페이지를 둘러보던 중 [튜토리얼](https://developer-1px.github.io/adorable-css/tutorial)에 스크롤 관련 오류가 있는 것 같아 문의드립니다. 튜토리얼의 스크롤이 다른 항목으로 넘어가도 고정되어 있어, 스크롤이 내려가 있는 상태에서 "길이가 짧아 그 스크롤까지 내릴 수 없는 항목"을 선택하면 HTML과 스크롤바 부분이 변하지 않는 오류가 있는 것 같습니다.

예를 들어 5. Flexbox의 스크롤을 맨 아래로 내린 후 6. Position을 누르면 스크롤바가 제대로 동작하지 않으며 위로 스크롤하기 전까지는 Flexbox 관련 HTML 내용이 보입니다.

**Comment by developer-1px** [comment]
제보감사드립니다~ 빠르게 확인해서 수정해보겠습니다

**Comment by developer-1px** [comment]
스크롤 속성이 누락되어 있었네요. 수정하였습니다! 제보 감사합니다.
