### ISSUE TITLE
m p b 등에서 mx my같이 right left, top bottom 페어되는건 어떻게 생각하시나용??

### ISSUE THREAD

**Issue by kogoome** [developer-1px/adorable-css#64]
테일윈드에서 어도러블css로 넘어오려고 테스트하고있습니다.
종종 px-2 같은걸 자주 쓰는데 없어서 아쉽습니다.

**Comment by developer-1px** [comment]
1.3.2 mx, my, px, py, bx, by 등 Box-model에서 좌우, 상하 페어로 값을 입력하는 Rule을 추가하였습니다.
확인 부탁드립니다.

**Comment by kogoome** [comment]
와 이렇게 빠르게 늘 감사합니다!
