### ISSUE TITLE
.vbox 내부의 .h(fill).scroll 이 예상대로 동작하지 않습니다

### ISSUE THREAD

**Issue by dolsup** [developer-1px/adorable-css#77]
# 문제상황

`.vbox > .h(fill).scroll` 이 fixed header를 제외한 부모 vbox의 남은 공간을 채우고 scrollable 해지는 것을 기대했지만 h(fill)이 부모 밖으로 나옵니다.
```html
<h2>.vbox > .h(fill).scroll</h2>
<div class="vbox w(fill) h(300) gap(10) b(orange) p(10)">
  <div class="h(50) bg(orange) pack">fixed header</div>
  <div class="vbox h(fill) scroll p(10) gap(10) bg(yellow)">
    <div class="bg(red) h(100) pack">
      item in long list
    </div>
    <div class="bg(red) h(100) pack">
      item in long list
    </div>
    <div class="bg(red) h(100) pack">
      item in long list
    </div>
  </div>
</div>
```

반면 `.hbox > .w(fill).scroll`은 잘 동작합니다.
```html
<h2>.hbox > .w(fill).scroll</h2>
<div class="w(350) hbox(fill) gap(10) b(orange) p(10)">
  <div class="w(50) bg(orange) pack">fixed</div>
  <div class="hbox w(fill) scroll p(10) gap(10)  bg(yellow)">
    <div class="bg(red) w(200) pack">
      item in long list
    </div>
    <div class="bg(red) w(200) pack">
      item in long list
    </div>
    <div class="bg(red) w(200) pack">
      item in long list
    </div>
  </div>
</div>
```

# 관련이 있을 것으로 추정되는 코드

https://github.com/developer-1px/adorable-css/blob/a25abe42310acb49260df101fc5c991dd2fc6950/packages/vite/src/core/rules.ts#L151-L155

w(fill)에는 flex-shrink: 1, max-width: 100% 같은 속성이 있는데

https://github.com/developer-1px/adorable-css/blob/a25abe42310acb49260df101fc5c991dd2fc6950/packages/vite/src/core/rules.ts#L180-L182

h(fill)에는 없습니다.

위 문제상황에서 `.h(fill).scroll`에 `.shrink`를 추가하면 원하는 대로 동작합니다.

**Comment by developer-1px** [comment]
제보해주신 내용 확인 했으며 새롭게 추가된 `h(fill)`에 `flex-shrink:1;max-height:100%;` 이 누락되어 있는 것을 확인했고 수정하였습니다.
너무 감사드립니다.

해당 수정 내용은 1.5.3 버전에 반영 되었습니다! 감사합니다.
