### ISSUE TITLE
vbox > .h(50).w(fill) 이 예상대로 동작하지 않습니다

### ISSUE THREAD

**Issue by dolsup** [developer-1px/adorable-css#78]
# 문제상황
```html
<h2>.vbox(?) > .h(?).w(fill)</h2>
<div class="vbox(center) w(fill) h(300) gap(10) b(orange) p(10)">
  <div class="h(50) w(fill) bg(orange) pack">fixed header</div>
  <div class="vbox h(fill) scroll w(300) p(10) gap(10) bg(yellow) shrink">
    <div class="bg(red) h(200) pack">
      item in long list
    </div>
    <div class="bg(red) h(200) pack">
      item in long list
    </div>
    <div class="bg(red) h(200) pack">
      item in long list
    </div>
  </div>
</div>
```

w(fill)은 flex-shrink: 1이 적용되기 때문에, vbox 하위 요소에 w(fill)을 지정하면 높이가 지정되어있어도 shrink될 수 있습니다.
<img width="220" alt="스크린샷 2023-10-05 오후 5 32 29" src="https://github.com/developer-1px/adorable-css/assets/8360934/b982e0d9-5bc4-414a-aeea-be990f673b59">

vbox의 기본값은 fill 이니까 하위 요소에 w(fill)을 지정하지 않으면 괜찮지만, vbox(center)등 fill이 아닌 다른 값을 지정했을 때는 일부 자식 요소에 w(fill)를 명시적으로 지정해야하는 경우가 있습니다.

<img width="355" alt="스크린샷 2023-10-05 오후 5 24 28" src="https://github.com/developer-1px/adorable-css/assets/8360934/3bb59ba6-e507-46cb-9855-7afe4901480e">

Figma에서 오토레이아웃을 이용해 같은 레이아웃을 만들어보고 handshake 플러그인을 이용해 adorable-css로 바꿔 보았습니다.

`Fill x 50`인 빨간 사각형이 shrink 됩니다.

`.vbox > .w(fill)` 에는 flex-shrink: 0이 적용되어야 할 것 같습니다.

**Comment by dolsup** [comment]
workaround는 3가지 정도가 있었습니다.

`.h(50).w(fill)`을
1. `.h(hug).w(fill)` 요소로 감싸기
2. `h(50)`을 `h(50~)`로 바꾸기
3. `no-shrink` 추가

**Comment by dolsup** [comment]
빠른 픽스 감사합니다!!

**Comment by developer-1px** [comment]
제보 너무 감사합니다!! 아직은 공개라기보다는 계속 다듬고 있는 중이므로 혹시 필요한 기능이나 문법이나 스펙등이 있다면 편하게 이슈 등록해주세요!! 고맙습니다.
